Repository ros2/rcl_interfaces, pull requests merged in 2019-05, with the labels that each got.

#77 Build interfaces from the package test_interface_files
  test_msgs/CMakeLists.txt
  test_msgs/action/Fibonacci.action
  test_msgs/action/NestedMessage.action
  test_msgs/include/test_msgs/message_fixtures.hpp
  test_msgs/include/test_msgs/service_fixtures.hpp
  test_msgs/msg/BoundedArrayNested.msg
  test_msgs/msg/BoundedArrayPrimitives.msg
  test_msgs/msg/BoundedArrayPrimitivesNested.msg
  test_msgs/msg/DynamicArrayNested.msg
  test_msgs/msg/DynamicArrayPrimitives.msg
  test_msgs/msg/DynamicArrayPrimitivesNested.msg
  test_msgs/msg/DynamicArrayStaticArrayPrimitivesNested.msg
  test_msgs/msg/Empty.msg
  test_msgs/msg/Nested.msg
  test_msgs/msg/Primitives.msg
  test_msgs/msg/StaticArrayNested.msg
  test_msgs/msg/StaticArrayPrimitives.msg
  test_msgs/msg/StaticArrayPrimitivesNested.msg
  test_msgs/package.xml
  test_msgs/src/test_msgs/message_fixtures.py
  test_msgs/src/test_msgs/service_fixtures.py
  test_msgs/srv/Empty.srv
  test_msgs/srv/Primitives.srv
Labels: in review

#78 add WString tests
  test_msgs/include/test_msgs/message_fixtures.hpp
  test_msgs/src/test_msgs/message_fixtures.py
Labels: in review

#76 Add fields for response code to action_msgs/CancelGoal service
  action_msgs/srv/CancelGoal.srv
Labels: in review

#79 Add UTF-8 BOM to message_fixtures.hpp file
  test_msgs/include/test_msgs/message_fixtures.hpp
Labels: in review

#80 add test cases for UTF-8 encoded strings
  test_msgs/include/test_msgs/message_fixtures.hpp
  test_msgs/src/test_msgs/message_fixtures.py
Labels: enhancement, in review

#67 Add mapping file for ROS 1 bridge
  rcl_interfaces/CMakeLists.txt
  rcl_interfaces/mapping_rules.yaml
  rcl_interfaces/package.xml
Labels: in progress
